[package]
name = "redtux"
version = "0.1.0"
authors = ["Lucas Riutzel <lriutzel@gmail.com>"]

[dependencies]
clap = "2.29"
gio = "0.3.0"
rawr = "0.1.1"
gtk = "0.3"

[patch.crates-io]
rawr = { path = "../../rust/rawr" }
